### PR TITLE
tray icon and more

### PR DESCRIPTION
**Pull request by rafaelcastrocouto**
- tray icon option
 - autorun task option
 - dark theme
 - windows path fix '/'
 - aliases and tasks JSON static file save
 - styles in CSS

### CODE REVIEW

**Comment by krasimir** [comment]
Thanks for the pull request. Here are few things:

1. `http-server` is missing in the dependencies. If you fresh install the yez module `node ./node/index.js` fails because it can't find `http-server`
2. The message `Yez! back-end is running. Install the Chrome extension or open http://localhost` is misleading because the port is not shown. I mean `9172`. I guess should end up on `or open http://localhost:9172`.
3. Chrome extension is not working because it listens on `9172` port while it should listen on `9172 + 1`
4. Can you please remind me one more time why we need electron. Is it because of the tray icon?

All the rest is really nice. I really like the dark theme.

**Comment by rafaelcastrocouto** [comment]
I believe it's all fixed now ... (at least everything is working fine on my machine :wink:

Electron is indeed needed for the tray icon to appear.

**Comment by krasimir** [comment]
@rafaelcastrocouto can you please make one more commit with these changes https://github.com/krasimir/yez/commit/4fbb77991502a032ed7c1a81fe83d93677329962 Then the PR will be ready for merging.

**Comment by rafaelcastrocouto** [comment]
I did all the changes in your commit except for the `chrome/js/Yez.js` port change:

     var Yez = absurd.component('Yez', {
  	     host: 'localhost',
  	     port: 9172,  <- this will not work ... must be 9173 (it's the socket port)

**Comment by krasimir** [comment]
Yep, now I agree. Previously [it was](https://github.com/krasimir/yez/commit/4fbb77991502a032ed7c1a81fe83d93677329962#diff-b2be8dc7c4b39f79c985f198b4129f8cR7) different. Good to go now. Merging and thanks for contribution. 

P.S.
Let me also update the package in Chrome's web store.

**Comment by krasimir** [comment]
`2.1.0` version of the Yez! backend released.

**Comment by krasimir** [comment]
The Chrome extension in Google's web store is updated too.

**Comment by rafaelcastrocouto** [comment]
I feel like diamonds in the sky!!!! :laughing:

**Comment by rafaelcastrocouto** [comment]
Got to fix the readme.md port ...
`(Have in mind that when you run the backend of Yez! the app is available at http://localhost:9173/)`

**Comment by krasimir** [comment]
[Done](https://github.com/krasimir/yez/commit/659c7923655930a23298977b2d2a0865ca83f7eb).

**Pull request merged**
